ci:
  autoupdate_schedule: quarterly

default_stages: [pre-commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, jupyter]
      - id: ruff-format
        types_or: [python, jupyter]
        exclude: \.pyx$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: .*\/copilot\/.*
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        args: [--ignore-words-list, "statics,atomate,nd,te,titel,coo,slite,fro"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        # MD013: line length
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD034: bare URL used
        args: [--disable, MD013, MD033, MD041, MD034, "--"]
